name: CI # 워크 플로우 이름 지정

on: # 워크 플로우가 시작될 조건 지정
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest # 실행 환경 지정
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Get commit
        id: git
        run: |
          echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

      - name: Get latest version
        id: version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Git
        run: |
          echo Branch name is: ${{ github.ref_name }}
          echo Short sha: ${{ steps.git.outputs.short_sha }}
          echo Version is: ${{ steps.version.outputs.current-version }}
